-- MySQL Script generated by MySQL Workbench
-- 01/06/16 16:10:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema secretaria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `secretaria` ;

-- -----------------------------------------------------
-- Schema secretaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secretaria` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `secretaria` ;

-- -----------------------------------------------------
-- Table `funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `funcionario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `funcionario` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(40) NOT NULL,
  `Departamento` VARCHAR(20) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `RG` VARCHAR(11) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `Celular` VARCHAR(12) NOT NULL,
  `Endereco` VARCHAR(40) NOT NULL,
  `Bairro` VARCHAR(20) NOT NULL,
  `Cidade` VARCHAR(20) NOT NULL,
  `Numero_Imovel` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CPF_UNIQUE` ON `funcionario` (`CPF` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `RG_UNIQUE` ON `funcionario` (`RG` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administrador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `administrador` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(40) NOT NULL,
  `funcionario_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `funcionario_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_UNIQUE` ON `administrador` (`ID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_administrador_funcionário_idx` ON `administrador` (`funcionario_ID` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `Nome_UNIQUE` ON `administrador` (`Nome` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `materias_modulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materias_modulos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `materias_modulos` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(40) NOT NULL,
  `Carga_Horaria` INT(11) NOT NULL,
  `Descricao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `login_senha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `login_senha` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `login_senha` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(40) CHARACTER SET 'ucs2' NOT NULL,
  `Senha` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `funcionario_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Usuario_UNIQUE` ON `login_senha` (`Usuario` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_login_senha_funcionário1_idx` ON `login_senha` (`funcionario_ID` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `funcionario_ID_UNIQUE` ON `login_senha` (`funcionario_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matricula` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `matricula` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `materias_modulos_ID` INT(11) NOT NULL,
  `Criador_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_matricula_matérias_modulos1_idx` ON `matricula` (`materias_modulos_ID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_matricula_login_senha1_idx` ON `matricula` (`Criador_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `professor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `professor` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(40) NOT NULL,
  `Qualificação` VARCHAR(60) NOT NULL,
  `funcionario_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_UNIQUE` ON `professor` (`ID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_professor_funcionário1_idx` ON `professor` (`funcionario_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turma` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `turma` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Curso` VARCHAR(20) NOT NULL,
  `Qut_Max` INT(11) NOT NULL,
  `Qut_Min` INT(11) NOT NULL,
  `Criador_ID` INT(11) NOT NULL,
  `professor_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_turma_login_senha1_idx` ON `turma` (`Criador_ID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_turma_professor1_idx` ON `turma` (`professor_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aluno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `aluno` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(40) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `Cidade` VARCHAR(30) NOT NULL,
  `Bairro` VARCHAR(30) NOT NULL,
  `Endereco` VARCHAR(40) NOT NULL,
  `Numero_Imovel` INT(11) NOT NULL,
  `RG` VARCHAR(11) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Telefone` VARCHAR(11) NOT NULL,
  `Celular` VARCHAR(12) NOT NULL,
  `Email` VARCHAR(30) NOT NULL,
  `matricula_ID` INT(11) NOT NULL,
  `turma_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `matricula_ID`, `turma_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CPF_UNIQUE` ON `aluno` (`CPF` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `RG_UNIQUE` ON `aluno` (`RG` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_aluno_turma1_idx` ON `aluno` (`turma_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios_comun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios_comun` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios_comun` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(40) NOT NULL,
  `funcionario_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `funcionario_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_UNIQUE` ON `usuarios_comun` (`ID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_usuarios_comun_funcionário1_idx` ON `usuarios_comun` (`funcionario_ID` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
